version: "3.9"
services:
  api-service:
    build: 
      dockerfile: WUPS_Service/wups_service/wups_service/Dockerfile
    ports:
      - "8080:80"

  api-node:
    build: 
      dockerfile: Node-server/Dockerfile
    ports:
      - "3030:80"
    environment:
      NODE_ENV: docker
