version: "3.9"
services:
  data-uploader:
    build: 
      dockerfile: data-processing/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb:/data/db

  api-service:
    build: 
      dockerfile: WUPS_Service/wups_service/wups_service/Dockerfile
    ports:
      - "8080:80"
    environment:
      ASPNETCORE_ENVIRONMENT: Docker

  api-node:
    build: 
      dockerfile: Node-server/Dockerfile
    ports:
      - "3030:3000"

volumes:
  mongodb: