version: "3.9"
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoadmin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - .:/mongodb_volumes

  api-service:
    build: 
      dockerfile: WUPS_Service/wups_service/wups_service/Dockerfile
    ports:
      - "8080:80"

  api-node:
    build: 
      dockerfile: Node-server/Dockerfile
    ports:
      - "3000:3000"